HEADERS = {
    'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
    'Accept-Language': 'en-US,en;q=0.5',
    'Connection': 'keep-alive',
}

URLS = [
'https://xn----8sbgjyicscimifi4nb5b.xn--p1ai/katalog/category/stoliki.html',
'https://xn----8sbgjyicscimifi4nb5b.xn--p1ai/katalog/category/skamejki.html',
'https://xn----8sbgjyicscimifi4nb5b.xn--p1ai/katalog/category/sportivnye-kompleksy-dlya-starshego-vozrasta.html',
'https://xn----8sbgjyicscimifi4nb5b.xn--p1ai/katalog/category/sportivnye-kompleksy-dlya-mladshego-vozrasta.html',
'https://xn----8sbgjyicscimifi4nb5b.xn--p1ai/katalog/category/igrovye-paneli.html',
'https://xn----8sbgjyicscimifi4nb5b.xn--p1ai/katalog/category/gorki.html',
'https://xn----8sbgjyicscimifi4nb5b.xn--p1ai/katalog/category/besedki-i-domiki.html',
'https://xn----8sbgjyicscimifi4nb5b.xn--p1ai/katalog/category/kacheli.html',
'https://xn----8sbgjyicscimifi4nb5b.xn--p1ai/katalog/category/vsesezonnye-detskie-ploshchadki.html',
'https://xn----8sbgjyicscimifi4nb5b.xn--p1ai/katalog/category/detskie-ploshchadki-dlya-pomeshchenij.html',
'https://xn----8sbgjyicscimifi4nb5b.xn--p1ai/katalog/category/savushka-master-2.html',
'https://xn----8sbgjyicscimifi4nb5b.xn--p1ai/katalog/category/master.html',
'https://xn----8sbgjyicscimifi4nb5b.xn--p1ai/katalog/category/savushka-4-sezona.html',
'https://xn----8sbgjyicscimifi4nb5b.xn--p1ai/katalog/category/savushka-baby-club.html',
'https://xn----8sbgjyicscimifi4nb5b.xn--p1ai/katalog/category/savushka-baby.html',
'https://xn----8sbgjyicscimifi4nb5b.xn--p1ai/katalog/category/savushka-neposeda.html',
'https://xn----8sbgjyicscimifi4nb5b.xn--p1ai/katalog/category/savushka-baza.html',
'https://xn----8sbgjyicscimifi4nb5b.xn--p1ai/katalog/category/savushka-toosun.html',
'https://xn----8sbgjyicscimifi4nb5b.xn--p1ai/katalog/category/malysham.html',
'https://xn----8sbgjyicscimifi4nb5b.xn--p1ai/katalog/category/detyam-starshe.html',
'https://xn----8sbgjyicscimifi4nb5b.xn--p1ai/katalog/category/savushka-lyuks.html',
'https://xn----8sbgjyicscimifi4nb5b.xn--p1ai/katalog/category/savushka-master.html',
'https://xn----8sbgjyicscimifi4nb5b.xn--p1ai/katalog/category/savushka.html',
'https://xn----8sbgjyicscimifi4nb5b.xn--p1ai/katalog/category/savushka-black.html',
'https://xn----8sbgjyicscimifi4nb5b.xn--p1ai/katalog/category/aksessuary-savushka.html',
'https://xn----8sbgjyicscimifi4nb5b.xn--p1ai/katalog/category/dopolnitelnoe-oborudovanie-romana.html',
'https://xn----8sbgjyicscimifi4nb5b.xn--p1ai/katalog/category/igrovye-kompleksy-dlya.html',
'https://xn----8sbgjyicscimifi4nb5b.xn--p1ai/katalog/category/igrovye-kompleksy-dlya-starshego-vozrasta.html',
]